Warehouse.Web/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace Warehouse.Web.Models
{
    public class Category
    {
        [Key]
        public long CategoryId { get; set; }
        public string Name { get; set; }
    }
}

Warehouse.Web/Models/Client.cs
using System.ComponentModel.DataAnnotations;

namespace Warehouse.Web.Models
{
    public class Client
    {
        [Key]
        public long ClientId { get; set; }
        public string CompanyName { get; set; }
        public string Bulstat { get; set; }
        public string PCP { get; set; } // Prison Candidate Person. (МОЛ)
        public string Address { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    }
}

Warehouse.Web/Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace Warehouse.Web.Models
{
    public class Employee
    {
        [Key]
        public long EmployeeId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    }
}

Warehouse.Web/Models/ErrorViewModel.cs
using System;

namespace Warehouse.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Warehouse.Web/Models/Order.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Warehouse.Web.Models
{
    public class Order
    {
        [Key]
        public long OrderId { get; set; }
        public DateTime OrderDate { get; set; }
        public long EmployeeId { get; set; }
        public Employee Employee { get; set; }
        public DateTime DeliveryDate { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryCity { get; set; }
        public decimal OrderExpences { get; set; }
        public PaymentType PaymentType { get; set; }
        public DateTime PaymentDate { get; set; }
        public string Notes { get; set; }
        public decimal TotalPrice{ get; set; }
        public long ClientId { get; set; }
        public Client Client { get; set; }
    }

    public enum PaymentType
    {
        Cash,
        Check,
        BankTransfer
    }
}

Warehouse.Web/Models/OrderDetails.cs
using System.ComponentModel.DataAnnotations;

namespace Warehouse.Web.Models
{
    public class OrderDetails
    {
        [Key]
        public long OrderDetailsId { get; set; }
        public long OrderId { get; set; }
        public Order Order { get; set; }
        public long ProductId { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
        public double DiscountPercentage { get; set; }
    }
}

Warehouse.Web/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Warehouse.Web.Models
{
    public class Product
    {
        [Key]
        public long ProductId { get; set; }
        public string Name { get; set; }
        public long CategoryId { get; set; }
        public Category Category { get; set; }
        public int MinQuantity { get; set; }
        public int OrderedQuantity { get; set; }
        public int DeliveredQuantity { get; set; }
        public int AvailableQuantity { get; set; }
        public decimal Price { get; set; }
        public Supplier Supplier { get; set; }
        public long SupplierId { get; set; }
    }
}

Warehouse.Web/Models/Supplier.cs
using System.ComponentModel.DataAnnotations;

namespace Warehouse.Web.Models
{
    public class Supplier
    {
        [Key]
        public long SupplierId { get; set; }
        public string CompanyName { get; set; }
        public string EmployeeName { get; set; }
        public string PhoneNumber { get; set; }
    }
}

Warehouse.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Warehouse.Web.Models;

namespace Warehouse.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Warehouse.Web/Controllers/WarehouseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Warehouse.Web.DTOs;
using Warehouse.Web.Models;
using Warehouse.Web.Services.Contracts;

namespace Warehouse.Web.Controllers
{
    [Authorize]
    public class WarehouseController : Controller
    {
        private readonly IWarehouseService warehouseService;
        private readonly IExcelGeneratorService excelGenerator;

        public WarehouseController(IWarehouseService warehouseService, IExcelGeneratorService excelGenerator)
        {
            this.warehouseService = warehouseService;
            this.excelGenerator = excelGenerator;
        }

        public IActionResult Search(Filter filter)
        {
            IEnumerable<Product> products;

            if (filter.CategoryId == 0 && string.IsNullOrEmpty(filter.SearchText))
                products = warehouseService.GetAllProducts();
            else
                products = warehouseService.GetFilteredProducts(filter);

            var model = new SearchViewModel()
            {
                Products = products,
                Categories = warehouseService.GetAllCategories(),
                Filter = filter
            };

            return View(model);
        }

        public async Task<IActionResult> ExportProduct(long id)
        {
            var product = warehouseService.GetProductById(id);
            var exportExcel = excelGenerator.GenerateProductExportAndWriteToMemoryStream(product);
            var isRemoved = await warehouseService.RemoveProduct(id);

            if (isRemoved)
                return File(exportExcel,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "report.xlsx");
            else
            {
                return NotFound();
            }
        }

        [HttpGet]
        public IActionResult AddProduct()
        {
            var viewModel = new AddProductViewModel()
            {
                Categories = warehouseService.GetAllCategories(),
                Suppliers = warehouseService.GetAllSuppliers()
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(AddProductInputModel product)
        {
            try
            {
                var productId = await this.warehouseService.AddProduct(product);
                return RedirectToAction(nameof(Search));
            }
            catch (Exception ex)
            {
                return BadRequest(ex);
            }

        }
    }
}

Warehouse.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>Wellcome to my WAREHOUSE App !</h1>
</div>

Warehouse.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Warehouse.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Warehouse</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Warehouse" asp-action="Search">Search</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark font-weight-bold" asp-area="" asp-controller="Warehouse" asp-action="AddProduct">Import Product</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Warehouse.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Warehouse.Web/Views/Warehouse/AddProduct.cshtml
@model Warehouse.Web.DTOs.AddProductViewModel

<div class="container-fluid text-center">
    <h2>Import Product</h2>
    <hr />
    <div class="row d-flex justify-content-center text-center">
        <form class="col-8 text-center" method="post">
            <div class="form-group">
                <label for="name">Product Name</label>
                <input type="text" class="form-control" id="name" name="Name">
            </div>
            <div class="form-group">
                <label for="category">Category</label>
                <select class="form-control " id="category" name="CategoryId" asp-items="@(new SelectList(Model.Categories, "CategoryId", "Name"))">
                </select>
            </div>
            <div class="form-group">
                <label for="minQuantity">Min Quantity</label>
                <input type="number" class="form-control" id="minQuantity" name="MinQuantity">
            </div>
            <div class="form-group">
                <label for="AvailableQuantity">Available Quantity</label>
                <input type="number" class="form-control" id="AvailableQuantity" name="AvailableQuantity">
            </div>
            <div class="form-group">
                <label for="price">Price</label>
                <input type="text" class="form-control" id="price" name="Price">
            </div>
            <div class="form-group">
                <label for="supplier">Min Quantity</label>
                <select class="form-control" id="supplier" name="SupplierId" asp-items="@(new SelectList(Model.Suppliers, "SupplierId", "CompanyName"))">
                </select>
            </div>
            <button type="submit" asp-action="AddProduct" class="btn btn-success">Create</button>
        </form>
    </div>
</div>

Warehouse.Web/Views/Warehouse/Search.cshtml
@model Warehouse.Web.DTOs.SearchViewModel

<div class="container-fluid">
    <h2>Do we have it in stock? Not sure? Just Search for it!</h2>
    <form class="form-group" asp-controller="Warehouse" asp-action="Search" method="post">
        <div class="md-form active-pink active-pink-2 mb-3 mt-0 row">
            <select class="form-control col-2" asp-for="Filter.CategoryId" asp-items="@(new SelectList(Model.Categories, "CategoryId", "Name"))">
                <option>All</option>
            </select>
            <input asp-for="Filter.SearchText" class="form-control search-field col-6" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-danger col-1 search-btn" type="submit">Search</button>
        </div>
    </form>

    <div class="col-10">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">Min Quantity</th>
                    <th scope="col">Ordrered Quantity</th>
                    <th scope="col">Delivered Quantity</th>
                    <th scope="col">Available Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col">Supplier</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var product in Model.Products)
                {
                    <tr>
                        <th scope="row">@product.ProductId</th>
                        <td>@product.Name</td>
                        <td>@product.Category.Name</td>
                        <td>@product.MinQuantity</td>
                        <td>@product.OrderedQuantity</td>
                        <td>@product.DeliveredQuantity</td>
                        <td>@product.AvailableQuantity</td>
                        <td>@product.Price</td>
                        <td>@product.Supplier.CompanyName</td>
                        <td><a asp-controller="Warehouse" asp-action="ExportProduct" asp-route-id="@product.ProductId">Export Product</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>